#!/bin/bash
#
# Startup script for the UFTP client
#

if [ ! -e ${HOME}/.uftp/ ]; then
    mkdir -m 700 ${HOME}/.uftp/
fi


for f in /etc/unicore/uftp/*; do
    if [ ! -e ${HOME}/.uftp/`basename $f` ]; then
	cp $f ${HOME}/.uftp/`basename $f`
        chmod 600 ${HOME}/.uftp/`basename $f`
    fi
done


#
# where the UFTP jar files are
#
UFTP_LIB=@lib@

#
# Java command 
#
JAVA=${JAVA:-java}

#
# helper function to set an option if it is not already set
#
# arg1: option name (without leading "-", e.g "Dlog4j.configuration")
# arg2: option value (e.g. =conf/extensions)
#
Options=( )
set_option(){
    if [[ "$UCC_OPTS" != *$1* ]]
        then
		N=${#Options[*]}
		Options[$N]="-$1$2"
	fi
}


#
# Options to the Java VM
#

#
# Memory for the VM
#
set_option "Xmx" "256m"

#set this one if you have ssl problems and need debug info
#OPTS=$OPTS" -Djavax.net.debug=ssl,handshake"

#
# log configuration
#
set_option "Dlog4j.configurationFile" "=file://${HOME}/.uftp/logging.properties"


#
# Java classpath
#
CP=$(find "$UFTP_LIB" -name "*.jar" -exec printf ":{}" \; )
	
export CLASSPATH=$CP

#
# go
#
# wildcards need to be escaped (otherwise they will be expanded by the shell)
$JAVA "${Options[@]}" $DEFS eu.unicore.uftp.standalone.ClientDispatcher ${1+"$@"}

