/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_unicore_uftp_server_unix_UnixGroup */

#ifndef _Included_eu_unicore_uftp_server_unix_UnixGroup
#define _Included_eu_unicore_uftp_server_unix_UnixGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_unicore_uftp_server_unix_UnixGroup
 * Method:    lookupByName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_unicore_uftp_server_unix_UnixGroup_lookupByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_unicore_uftp_server_unix_UnixGroup
 * Method:    lookupByGid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_unicore_uftp_server_unix_UnixGroup_lookupByGid
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
